apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bootstrap
  description: A collection of kickstart scripts for setting up development environments
  tags:
    - shell
spec:
  type: library
  lifecycle: production
  owner: johnnyhuy